### PR TITLE
Better documentation for wrap-character

### PR DESCRIPTION
**Pull request by sommerluk**
Documentation as proposed in https://github.com/mapnik/mapnik/issues/3885#issuecomment-388018876

### CODE REVIEW

**Comment by nebulon42** [comment]
This wasn't introduced in 3.0.20 right? So the change should also go into the other API files.

**Comment by sommerluk** [comment]
Yes. But the question is: When was this feature introduces? The api documentation starts with version 2.0, but I guess the current behaviour based on ICU was introduced [in a commit in 2014](https://github.com/mapnik/mapnik/commit/e4c895d4c1461d451812594206650cf4cac2c1d0) which might mean that it is present since version 3.0. Is this correct?

**Comment by talaj** [comment]
> it is present since version 3.0. Is this correct?

Yes, you are correct, the documentation is valid for all 3.0 versions of Mapnik.

**Comment by sommerluk** [comment]
PR updated. Ready.

**Comment by nebulon42** [comment]
Thanks!

**Pull request merged**
