### PR TITLE
remove image-filters from symbolizers

### PR DESCRIPTION
**Pull request by talaj**
Image filters don't work on symbolizers, only on styles.

### CODE REVIEW

**Comment by nebulon42** [comment]
Does this only apply to 3.0.6 or should this be part of earlier API versions too?

**Comment by springmeyer** [comment]
I think this change makes sense from a mapnik perspective. However I also have a recollection that the carto.js design led to the placement here. I would prefer the organization of mapnik-reference be modeled directly on mapnik design, and that carto.js be adapted. But I recall that was beyond my understanding of carto.js at the time. I presume to keep carto.js working (specifically the ability to apply image filters on styles) with this change the code around https://github.com/mapbox/carto/blob/7e52b50dcebf05d895f3c48e96514bed8ad63cdf/lib/carto/tree/definition.js#L106-L108 would need to be adapted.

**Comment by springmeyer** [comment]
@nebulon42 - would you be able to make this cleanup change? I think carto would need updated and the mapnik-reference docs. But it seems like the right thing to clean this up (in all versions).

**Comment by nebulon42** [comment]
The change is no problem, we have to change the way how the reference is processed (https://github.com/mapbox/carto/blob/master/lib/carto/tree/reference.js#L50-L60). We then should go all the way and remove the * symbolizer completely. Internally it still will be used, but in a different way.

I should add that my view of mapnik-reference is maybe a bit different than that of Mapnik devs. I see mapnik-reference belonging more to the carto side than the Mapnik side. I could easily imagine carto to not exclusively output Mapnik XML one day. I'm also planning to make it possible to replace mapnik-reference with your own version via the API. (ref https://github.com/mapbox/carto/issues/413)

That said I think that mapnik-reference is a very nice and helpful construct. But carto has to establish the format of the reference not the other way round.

**Comment by nebulon42** [comment]
carto is updated and I pushed a commit in this branch that removes the * symbolizer completely. If somebody could review again, this would be great.

**Comment by nebulon42** [comment]
This also affects the API reference generated on mapnik.org. So that should be updated as well.

**Comment by nebulon42** [comment]
I have updated the website code to include style and layer reference.

**Pull request merged**
