### PR TITLE
First site version

### PR DESCRIPTION
**Pull request by yohanboniface**
cf mapnik/mapnik.github.com#25

Very basic first version, but should cover simple needs.

When this got merged, next steps are:
- [x] move to `gh-pages` branch as default branch (and delete `master` to avoid confusion in the future)
- [x] enable the github pages
- [ ] DNS entry with the domain to be used: see https://help.github.com/articles/tips-for-configuring-a-cname-record-with-your-dns-provider/
- [ ] add a CNAME with the future domain to be used

Not sure about the domain we want:
- api.mapnik.org (but one can think it's the C++ API)
- doc.mapnik.org
- reference.mapnik.org

cc @springmeyer for a feedback :)

screenshot from 2015-08-04 10 53 34

### CODE REVIEW

**Comment by yohanboniface** [comment]
@springmeyer just pushed a `gh-pages` branch so we can enable the site, which will be easier to review it and give feedback (even if it's not official yet). But I don't have the permissions to enable the Github Pages, can you do that for me? :)

**Comment by springmeyer** [comment]
@yohanboniface - thank you!!!!! This looks great. I see it is viewable at http://mapnik.org/mapnik-reference/. I am just back from being away but I'll give thought to cnames when I have a moment. Thanks!

**Comment by yohanboniface** [comment]
> I am just back from being away but I'll give thought to cnames when I have a moment.

Cool, thanks, no hurry :) I just wanted to have a browsable version, so we can have feedback ;)

(And I'm about to be offline too for two weeks (sailing :) ).

**Comment by talaj** [comment]
Maybe I'm not looking to the right place but I don't see reference for `Layer` and `Style`.

**Comment by yohanboniface** [comment]
> Maybe I'm not looking to the right place but I don't see reference for Layer and Style.

No, you're right. Not really a strong choice but I've only displayed the symbolizers reference. I'll see how I can add also the other sections without adding confusion in the page :)

**Comment by yohanboniface** [comment]
@springmeyer quick reminder: I think we should not forget to switch to `gh-pages` as default branch, otherwise we'll spend time merging from one to the other as soon as we'll have pull requests (and I don't have the permissions to do so). Other listed tasks can be done with calm, I'd say :)

**Comment by springmeyer** [comment]
I've just moved `gh-pages` to be the default branch, deleted `master`, and deleted this pull branch `site` since I can see gh-pages was already ahead. I think http://mapnik.org/mapnik-reference/ as a url is just fine - nothing more needed in my opinion. Thank you again @yohanboniface for this effort!

**Pull request closed without merging**
