### PR TITLE
Add repeat-wrap-character ref in 3.0.0

### PR DESCRIPTION
**Pull request by yohanboniface**
Not sure I got it all right, but could be at least a starting point :)

Thanks for reviewing! :)

### CODE REVIEW

**Comment by yohanboniface** [comment]
@springmeyer do you plan to integrate `repeat-wrap-character` in the reference, now that Mapnik 3.0 is on track? :)

**Comment by springmeyer** [comment]
@yohanboniface - I've still not had time to fully research all the potential aspects of whether it option is working perfectly. But I think we should merge this and keep testing and iterating. Thanks for confirming it works as you need.

**Comment by springmeyer** [comment]
@yohanboniface - invited to you be a committer on mapnik-reference, so feel free to:

1) merge this
2) add a note to the changelog (and create a 7.0.3 entry for it)
3) have a look around if you see any other things needed for 7.03
4) after that we can work together to tag/release.

**Comment by yohanboniface** [comment]
@springmeyer thanks for the confidence, I'll try to deserve it :)
About a new release: seems that `7.0.2` hasn't been released yet, so it seems we can add on this instead of creating `7.0.3`.

Suggestion of workflow: I've created a `7.0.2` label and started tagging pull requests and issues: can you quickly check that you agree with the selection, and add or remove labels when needed? And then I'll take care of merging/refining them, adding appropriate changelogs and preparing for releasing.

Tell me if that workflow suggestion is ok for you :)

**Comment by springmeyer** [comment]
sounds good!

**Comment by springmeyer** [comment]
@yohanboniface - thanks again for curating the `7.0.2` milestone. The help is huge! Often times in open source we thing we don't have time for something, when in fact we just don't have energy left. Thank you for sharing your energy.

**Pull request merged**
