### PR TITLE
add text-largest-bbox-only

### PR DESCRIPTION
**Pull request by talaj**
Adds missing property of text symbolizer.

### CODE REVIEW

**Comment by yohanboniface** [comment]
@springmeyer I see [in the wiki](https://github.com/mapnik/mapnik/wiki/TextSymbolizer) that this option is sort of experimental (*NOTE: this option may change or be renamed in the future*), should we think about some `"experimental": true` key to add in the symbolizer in such case?

**Comment by talaj** [comment]
Also the description of this option on the wiki is not very precise. One have to use this option for labeling multi geometries, not just polygons.

**Comment by springmeyer** [comment]
> @springmeyer I see in the wiki that this option is sort of experimental (NOTE: this option may change or be renamed in the future)

Yes, I've hesitated to add this because I'd love to replace it https://github.com/mapnik/mapnik/issues/1583. @talaj - what do you think: is the idea of being able to control labeling like that a good idea? If not then I should probably just stop hesitating and expose this option.

> should we think about some "experimental": true key to add in the symbolizer in such case?

I think better to just make a call as per above.

**Comment by yohanboniface** [comment]
> I think better to just make a call as per above.

Seems to me that it's not the first case of feature that exists in Mapnik for a long but doesn't pop up on mapnik-reference because it's not considered stable enough. My opinion is that it would be much helpful for the community to add those features as soon as they exist, but with a key that define their stability status.
Just an example: when using carto, if a symbolizer is not on mapnik-reference you just can't use it, so you can't even test it and give feedback to make it better.
Another suggestion for the key: `stability`, with the values `deprecated`, `experimental`, `unstable` and `stable`, the default being `stable` so we don't need to add the key everywhere.
Thoughts @springmeyer ? :)

**Comment by springmeyer** [comment]
> Another suggestion for the key: stability, with the values deprecated, experimental, unstable and stable, the default being stable so we don't need to add the key everywhere.

Okay, thanks for pushing back: I'm in. We definitely need a way to tag things as deprecated. And so I like combining this into a single `stability` (or `status`) category. :+1: to `stable` being default so we only need the key added in rare circumstances.

**Comment by yohanboniface** [comment]
Excellent :)
Should I prepare that for `7.0.2`? (I guess we need to describe it in datasource.template.json?)
If so, I'll create another issue for tracking this.

**Comment by yohanboniface** [comment]
Well, it may require an upgrade of at least the minor tag, so we may target `7.1.0` instead, if not `8.0.0`, but I'm not sure what is the policy for versioning. :)

**Comment by springmeyer** [comment]
I think we should go to 8.0.0 because this will add to the reference scheme. It won't be breaking but will still be significant.

**Comment by talaj** [comment]
@springmeyer It's definitely good idea to use something like 'multi-policy' enumeration instead. Also default behavior should change. I was always thinking something is broken when just one geometry of multigeometry get labeled.

**Pull request merged**
