### PR TITLE
Line pattern "repeat"

### PR DESCRIPTION
**Pull request by talaj**
Adds `line-pattern-type` and related options introduced to Mapnik in https://github.com/mapnik/mapnik/pull/3980. The functionality will be part of Mapnik 3.0.22 ideally, once https://github.com/mapnik/mapnik/pull/4004 get merged.

### CODE REVIEW

**Comment by sommerluk** [comment]
@talaj Thanks!

**Comment by kocio-pl** [comment]
@talaj Hi, is there a chance to make v3.0.22 release and merge this code?

**Comment by talaj** [comment]
Hi @kocio-pl, I will try to speed it up.

**Comment by talaj** [comment]
So [Mapnik 3.0.22](https://github.com/mapnik/mapnik/releases/tag/v3.0.22) is out. I will try to finish this PR.

**Review by artemp — APPROVED** [review]
Looking great

**Comment by sommerluk** [comment]
Thanks @talaj for doing all the work for implementing the polygon-like patterns!

**Pull request merged**
