### PR TITLE
add line- and polygon-pattern-transform option

### LINKED ISSUE #120: Support PolygonPatternSymbolizer's transform property
Ref https://github.com/mapbox/carto/issues/445

### PR DESCRIPTION
**Pull request by nebulon42**
Fixes #120.

### CODE REVIEW

**Comment by springmeyer** [comment]
👍 Looks good to merge once travis is green. I've invited you just now to be a committer to this repo so you can merge. Let me know if you'd also like npm publish access.

**Comment by springmeyer** [comment]
> once travis is green

Oddly travis is not building the commit yet. Perhaps there is some latency today between apis?

**Comment by nebulon42** [comment]
Thanks Dane! You have given me npm access when I was granted npm access to carto. :)
I have no idea why travis is not triggered. I have run npm test locally and it succeeded. But will wait.

**Comment by nebulon42** [comment]
@springmeyer It seems to me that there was no CI on PRs after merging master into gh-pages.

**Comment by springmeyer** [comment]
Can you rebase this branch from `gh-pages` latest branch after #129? Then see if this builds on travis?

**Comment by springmeyer** [comment]
Thanks!

**Pull request merged**
