### PR TITLE
remove dynamic loading for browser contexts

### LINKED ISSUE #116: Abandon dynamic loading for browser contexts
I'm currently attempting browserification of Carto and mapnik-reference will have to change too to support it. Dynamic loading i.e. using require with variables is not supported in a browser context.

So we would have to move to requiring all versions explicitly. This has the obvious downside that all versions have to be loaded, which may not be necessary outside of a browser context. Another possibility would be to detect if being in a browser context (e.g. http://stackoverflow.com/a/31090240) and only then requiring all the versions.

I can provide a patch, but the general direction would have to be clarified first.
Thoughts?

### PR DESCRIPTION
**Pull request by nebulon42**
Fixes #116.

Browser context is tested for by assessing ~~the presence of the `window` variable~~ `process.browser`. Unfortunately, it comes with explicitly listing the versions and thus more maintenance effort. This cannot be avoided.

Dynamic loading is kept if there is no browser context detected.

### CODE REVIEW

**Comment by tmcw** [comment]
process.browser is a reliable indicator of browser context

**Comment by nebulon42** [comment]
If you think that would be less verbose and/or more reliable I'm happy to change it.

**Comment by springmeyer** [comment]
Instead of hardcoding the versions, @nebulon42 - what do you think a build step to generate an alternative `index-browser.js`?

**Comment by nebulon42** [comment]
I'm not sure this would work well with tools like Browserify. While you could always require the browser specific variant this would push the load of ensuring browser compatibility of mapnik-reference to users of the lib like Carto. Or am I missing something here?

**Comment by nebulon42** [comment]
@springmeyer How should we proceed here?

**Comment by springmeyer** [comment]
@nebulon42 by "build" step I mean having a step we take before publishing that generates things like this list: https://github.com/nebulon42/mapnik-reference/blob/browser/index.js#L5-L14. The idea would be that instead of using `fs.readdirSync` for node or hardcoding the list for browsers we would use `fs.readdirSync` in a build step and auto-generate the index.js file. This way we could do releases without having the update the `index.js` manually for new versions but have the same code working for browsers and node. That make some sense?

**Comment by nebulon42** [comment]
Sounds good, I have now implemented a build step with lodash templates. It made sense for me to keep the distinction between browser and node because loading everything at once is only necessary in the browser context.

What is missing is an automated test if it actually works in a browser context (it does), but this would require PhantomJS, Selenium or the like.

**Comment by nebulon42** [comment]
@springmeyer I would be interested to hear what you think about this PR. This is the last piece that prevents Browserify support of Carto.

**Comment by nebulon42** [comment]
@mapnik/mapnik-reference I'm going to merge this soon, if there are no objections.

**Comment by springmeyer** [comment]
I have objections, see https://github.com/mapnik/mapnik-reference/commit/394e2396f4b50d8d64a4b3c7c7d4f5d1f150e929#commitcomment-20397440. Do you have ideas on how to maintain a working `npm install` via a git clone @nebulon42?

**Comment by nebulon42** [comment]
That's bad. I first wanted it to run on postinstall, but thought prepublish might be better suited, because it only has to run once then. But I missed that use-case. So we could still move from prepublish to postinstall. Or we could leave prepublish in place and try to detect if index.js is missing and generate it if needed on postinstall.

**Comment by nebulon42** [comment]
@springmeyer Should be fixed in latest master. If you think it is ok we can tag 8.6.1.

**Comment by springmeyer** [comment]
@nebulon42 - thank you I will test again and let you know. In the meantime, any reason you think using the `install` target rather than `pre/post` install would not work?

**Comment by nebulon42** [comment]
To be honest I thought install and postinstall were equivalent. But I have no preference if there is an advantage using the other one.

**Comment by springmeyer** [comment]
Okay, I trust your judgement on what is best. I've only used `install` before which is why I ask (most C++ node modules override install that use `node-pre-gyp`). Feel free to tag again now (I've confirmed that mapnik-swoop is working again: https://travis-ci.org/mapbox/mapnik-swoop/builds/190055081)

**Comment by nebulon42** [comment]
Done.

**Pull request merged**
